// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/kills.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KillData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KillerName    string                 `protobuf:"bytes,1,opt,name=KillerName,proto3" json:"KillerName,omitempty"`
	KillerID      int32                  `protobuf:"varint,2,opt,name=KillerID,proto3" json:"KillerID,omitempty"`
	KillerX       float32                `protobuf:"fixed32,3,opt,name=KillerX,proto3" json:"KillerX,omitempty"`
	KillerY       float32                `protobuf:"fixed32,4,opt,name=KillerY,proto3" json:"KillerY,omitempty"`
	KillerZ       float32                `protobuf:"fixed32,5,opt,name=KillerZ,proto3" json:"KillerZ,omitempty"`
	VictimName    string                 `protobuf:"bytes,6,opt,name=VictimName,proto3" json:"VictimName,omitempty"`
	VictimID      int32                  `protobuf:"varint,7,opt,name=VictimID,proto3" json:"VictimID,omitempty"`
	VictimX       float32                `protobuf:"fixed32,8,opt,name=VictimX,proto3" json:"VictimX,omitempty"`
	VictimY       float32                `protobuf:"fixed32,9,opt,name=VictimY,proto3" json:"VictimY,omitempty"`
	VictimZ       float32                `protobuf:"fixed32,10,opt,name=VictimZ,proto3" json:"VictimZ,omitempty"`
	Weapon        string                 `protobuf:"bytes,11,opt,name=Weapon,proto3" json:"Weapon,omitempty"`
	IsHeadshot    bool                   `protobuf:"varint,12,opt,name=IsHeadshot,proto3" json:"IsHeadshot,omitempty"`
	RoundNum      int32                  `protobuf:"varint,13,opt,name=RoundNum,proto3" json:"RoundNum,omitempty"`
	KillerTeam    string                 `protobuf:"bytes,14,opt,name=KillerTeam,proto3" json:"KillerTeam,omitempty"`
	KillerTeamID  string                 `protobuf:"bytes,15,opt,name=KillerTeamID,proto3" json:"KillerTeamID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillData) Reset() {
	*x = KillData{}
	mi := &file_protos_kills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillData) ProtoMessage() {}

func (x *KillData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillData.ProtoReflect.Descriptor instead.
func (*KillData) Descriptor() ([]byte, []int) {
	return file_protos_kills_proto_rawDescGZIP(), []int{0}
}

func (x *KillData) GetKillerName() string {
	if x != nil {
		return x.KillerName
	}
	return ""
}

func (x *KillData) GetKillerID() int32 {
	if x != nil {
		return x.KillerID
	}
	return 0
}

func (x *KillData) GetKillerX() float32 {
	if x != nil {
		return x.KillerX
	}
	return 0
}

func (x *KillData) GetKillerY() float32 {
	if x != nil {
		return x.KillerY
	}
	return 0
}

func (x *KillData) GetKillerZ() float32 {
	if x != nil {
		return x.KillerZ
	}
	return 0
}

func (x *KillData) GetVictimName() string {
	if x != nil {
		return x.VictimName
	}
	return ""
}

func (x *KillData) GetVictimID() int32 {
	if x != nil {
		return x.VictimID
	}
	return 0
}

func (x *KillData) GetVictimX() float32 {
	if x != nil {
		return x.VictimX
	}
	return 0
}

func (x *KillData) GetVictimY() float32 {
	if x != nil {
		return x.VictimY
	}
	return 0
}

func (x *KillData) GetVictimZ() float32 {
	if x != nil {
		return x.VictimZ
	}
	return 0
}

func (x *KillData) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *KillData) GetIsHeadshot() bool {
	if x != nil {
		return x.IsHeadshot
	}
	return false
}

func (x *KillData) GetRoundNum() int32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *KillData) GetKillerTeam() string {
	if x != nil {
		return x.KillerTeam
	}
	return ""
}

func (x *KillData) GetKillerTeamID() string {
	if x != nil {
		return x.KillerTeamID
	}
	return ""
}

type KillDataList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kills         []*KillData            `protobuf:"bytes,1,rep,name=Kills,proto3" json:"Kills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillDataList) Reset() {
	*x = KillDataList{}
	mi := &file_protos_kills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillDataList) ProtoMessage() {}

func (x *KillDataList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillDataList.ProtoReflect.Descriptor instead.
func (*KillDataList) Descriptor() ([]byte, []int) {
	return file_protos_kills_proto_rawDescGZIP(), []int{1}
}

func (x *KillDataList) GetKills() []*KillData {
	if x != nil {
		return x.Kills
	}
	return nil
}

var File_protos_kills_proto protoreflect.FileDescriptor

const file_protos_kills_proto_rawDesc = "" +
	"\n" +
	"\x12protos/kills.proto\"\xb6\x03\n" +
	"\bKillData\x12\x1e\n" +
	"\n" +
	"KillerName\x18\x01 \x01(\tR\n" +
	"KillerName\x12\x1a\n" +
	"\bKillerID\x18\x02 \x01(\x05R\bKillerID\x12\x18\n" +
	"\aKillerX\x18\x03 \x01(\x02R\aKillerX\x12\x18\n" +
	"\aKillerY\x18\x04 \x01(\x02R\aKillerY\x12\x18\n" +
	"\aKillerZ\x18\x05 \x01(\x02R\aKillerZ\x12\x1e\n" +
	"\n" +
	"VictimName\x18\x06 \x01(\tR\n" +
	"VictimName\x12\x1a\n" +
	"\bVictimID\x18\a \x01(\x05R\bVictimID\x12\x18\n" +
	"\aVictimX\x18\b \x01(\x02R\aVictimX\x12\x18\n" +
	"\aVictimY\x18\t \x01(\x02R\aVictimY\x12\x18\n" +
	"\aVictimZ\x18\n" +
	" \x01(\x02R\aVictimZ\x12\x16\n" +
	"\x06Weapon\x18\v \x01(\tR\x06Weapon\x12\x1e\n" +
	"\n" +
	"IsHeadshot\x18\f \x01(\bR\n" +
	"IsHeadshot\x12\x1a\n" +
	"\bRoundNum\x18\r \x01(\x05R\bRoundNum\x12\x1e\n" +
	"\n" +
	"KillerTeam\x18\x0e \x01(\tR\n" +
	"KillerTeam\x12\"\n" +
	"\fKillerTeamID\x18\x0f \x01(\tR\fKillerTeamID\"/\n" +
	"\fKillDataList\x12\x1f\n" +
	"\x05Kills\x18\x01 \x03(\v2\t.KillDataR\x05KillsB+Z)github.com/TheBigJayT/round-two-cs/protosb\x06proto3"

var (
	file_protos_kills_proto_rawDescOnce sync.Once
	file_protos_kills_proto_rawDescData []byte
)

func file_protos_kills_proto_rawDescGZIP() []byte {
	file_protos_kills_proto_rawDescOnce.Do(func() {
		file_protos_kills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_kills_proto_rawDesc), len(file_protos_kills_proto_rawDesc)))
	})
	return file_protos_kills_proto_rawDescData
}

var file_protos_kills_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_kills_proto_goTypes = []any{
	(*KillData)(nil),     // 0: KillData
	(*KillDataList)(nil), // 1: KillDataList
}
var file_protos_kills_proto_depIdxs = []int32{
	0, // 0: KillDataList.Kills:type_name -> KillData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_kills_proto_init() }
func file_protos_kills_proto_init() {
	if File_protos_kills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_kills_proto_rawDesc), len(file_protos_kills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_kills_proto_goTypes,
		DependencyIndexes: file_protos_kills_proto_depIdxs,
		MessageInfos:      file_protos_kills_proto_msgTypes,
	}.Build()
	File_protos_kills_proto = out.File
	file_protos_kills_proto_goTypes = nil
	file_protos_kills_proto_depIdxs = nil
}
