// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: protos/position.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	ID32          int32                  `protobuf:"varint,4,opt,name=ID32,proto3" json:"ID32,omitempty"`
	KillerName    string                 `protobuf:"bytes,5,opt,name=KillerName,proto3" json:"KillerName,omitempty"`
	DeadName      string                 `protobuf:"bytes,6,opt,name=DeadName,proto3" json:"DeadName,omitempty"`
	DeadX         float32                `protobuf:"fixed32,7,opt,name=DeadX,proto3" json:"DeadX,omitempty"`
	DeadY         float32                `protobuf:"fixed32,8,opt,name=DeadY,proto3" json:"DeadY,omitempty"`
	DeadZ         float32                `protobuf:"fixed32,9,opt,name=DeadZ,proto3" json:"DeadZ,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_protos_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_protos_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_protos_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Position) GetID32() int32 {
	if x != nil {
		return x.ID32
	}
	return 0
}

func (x *Position) GetKillerName() string {
	if x != nil {
		return x.KillerName
	}
	return ""
}

func (x *Position) GetDeadName() string {
	if x != nil {
		return x.DeadName
	}
	return ""
}

func (x *Position) GetDeadX() float32 {
	if x != nil {
		return x.DeadX
	}
	return 0
}

func (x *Position) GetDeadY() float32 {
	if x != nil {
		return x.DeadY
	}
	return 0
}

func (x *Position) GetDeadZ() float32 {
	if x != nil {
		return x.DeadZ
	}
	return 0
}

type Positions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pos           []*Position            `protobuf:"bytes,1,rep,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Positions) Reset() {
	*x = Positions{}
	mi := &file_protos_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Positions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Positions) ProtoMessage() {}

func (x *Positions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Positions.ProtoReflect.Descriptor instead.
func (*Positions) Descriptor() ([]byte, []int) {
	return file_protos_position_proto_rawDescGZIP(), []int{1}
}

func (x *Positions) GetPos() []*Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_protos_position_proto protoreflect.FileDescriptor

const file_protos_position_proto_rawDesc = "" +
	"\n" +
	"\x15protos/position.proto\"\xc6\x01\n" +
	"\bPosition\x12\f\n" +
	"\x01X\x18\x01 \x01(\x02R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x02R\x01Y\x12\f\n" +
	"\x01Z\x18\x03 \x01(\x02R\x01Z\x12\x12\n" +
	"\x04ID32\x18\x04 \x01(\x05R\x04ID32\x12\x1e\n" +
	"\n" +
	"KillerName\x18\x05 \x01(\tR\n" +
	"KillerName\x12\x1a\n" +
	"\bDeadName\x18\x06 \x01(\tR\bDeadName\x12\x14\n" +
	"\x05DeadX\x18\a \x01(\x02R\x05DeadX\x12\x14\n" +
	"\x05DeadY\x18\b \x01(\x02R\x05DeadY\x12\x14\n" +
	"\x05DeadZ\x18\t \x01(\x02R\x05DeadZ\"(\n" +
	"\tPositions\x12\x1b\n" +
	"\x03pos\x18\x01 \x03(\v2\t.PositionR\x03posB\x12Z\x10project_f/protosb\x06proto3"

var (
	file_protos_position_proto_rawDescOnce sync.Once
	file_protos_position_proto_rawDescData []byte
)

func file_protos_position_proto_rawDescGZIP() []byte {
	file_protos_position_proto_rawDescOnce.Do(func() {
		file_protos_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_position_proto_rawDesc), len(file_protos_position_proto_rawDesc)))
	})
	return file_protos_position_proto_rawDescData
}

var file_protos_position_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_position_proto_goTypes = []any{
	(*Position)(nil),  // 0: Position
	(*Positions)(nil), // 1: Positions
}
var file_protos_position_proto_depIdxs = []int32{
	0, // 0: Positions.pos:type_name -> Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_position_proto_init() }
func file_protos_position_proto_init() {
	if File_protos_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_position_proto_rawDesc), len(file_protos_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_position_proto_goTypes,
		DependencyIndexes: file_protos_position_proto_depIdxs,
		MessageInfos:      file_protos_position_proto_msgTypes,
	}.Build()
	File_protos_position_proto = out.File
	file_protos_position_proto_goTypes = nil
	file_protos_position_proto_depIdxs = nil
}
