on: pull_request

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
      - uses: yusufpapurcu/go-license-checker@v0.5
